### ISSUE TITLE
Extract metrics into own package?

### ISSUE THREAD

**Issue by jankapunkt** [Meteor-Community-Packages/meteor-elastic-apm#52]
Hey I have checked the code and I am curious, if it would be desirable and feasible to have a separate package for the metrics (that does not depend on the elastic api), which is 99% of the package as far as I can see.

Use case: I would like to send the raw metrics to my own apm server, which I will then process using R to generate a customized report. Does this make sense with the current package structure?

**Comment by kschingiz** [comment]
Hi, sorry for the long delay. 
Meteor specific metrics are based on this package: https://github.com/kschingiz/meteor-measured
Which is based on this package: https://github.com/yaorg/node-measured
You can implement your custom metrics reporter for your API easily.
Thanks!

**Comment by jankapunkt** [comment]
@kschingiz I understand but `meteor-measured` does not contain all the metrics from the [instrumenting](https://github.com/Meteor-Community-Packages/meteor-elastic-apm/tree/master/instrumenting) folder and the only dependency to elastic is from my point of view this line:

```javascript
const Agent = require('elastic-apm-node');
```

so if this package, for example, exports a function, that allows the agent to be injected then this package could be used 1:1 for other "Agents" than only elastic.
