### ISSUE TITLE
error: Conflict: Constraint email@1.2.3 is not satisfied by email 2.0.0.

### ISSUE THREAD

**Issue by rj-david** [Meteor-Community-Packages/meteor-elastic-apm#53]
Updated to Meteor 1.11 and got these errors

error: Conflict: Constraint email@1.2.3 is not satisfied by email 2.0.0.
Constraints on package "email":
* email@~2.0.0 <- top level
* email@1.2.3 <- kschingiz:meteor-elastic-apm 2.4.0

**Comment by linegel** [comment]
I have same problem, why do we even need email as a dependency for `meteor-elastic-apm`?

**Comment by linegel** [comment]
Afte quick look over source code looks like problem could be easily fixed by merging PR which I just opened #54

**Comment by SimonSimCity** [comment]
@linegel thanks for opening the PR. I'll see how soon I can release a new version or whether there's other stuff we should remove ...

**Comment by SimonSimCity** [comment]
Released as 2.4.1.
